/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medac.practica_intermodular;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Rivas Ceacero
 */
public class JFramePrincipal extends javax.swing.JFrame {

    HashMap<String, ArrayList<String>> optionsMap = new HashMap<>();

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        loadDataFromDatabase();
    }

    private void loadDataFromDatabase() {
        optionsMap = new HashMap<>();
        try {
            Connection connection = DatabaseConnection.getConnection();
            // Cargar las categorías (Planetas)
            String sqlPlanetas = "SELECT nombre FROM planetas";
            PreparedStatement statementPlanetas = connection.prepareStatement(sqlPlanetas); 
                ResultSet resultSetPlanetas = statementPlanetas.executeQuery();
                while (resultSetPlanetas.next()) {
                    String planeta = resultSetPlanetas.getString("nombre");
                    ComboBox_planetas.addItem(planeta);
                }
            

            // Cargar los satélites correspondientes
            String sqlSatelites = "SELECT p.nombre AS planeta, s.nombre AS satelite FROM planetas p JOIN satelites s ON p.id = s.planeta_id";
            Statement statementSatelites = connection.createStatement(); 
            ResultSet resultSetSatelites = statementSatelites.executeQuery(sqlSatelites);
                while (resultSetSatelites.next()) {
                    String planeta = resultSetSatelites.getString("planeta");
                    String satelite = resultSetSatelites.getString("satelite");
                    optionsMap.computeIfAbsent(planeta, k -> new ArrayList<>()).add(satelite);
                }
            
            // Cargar los datos del sol
            String sqlEstrellas = "SELECT * FROM Estrellas where nombre = 'Sol'";
            Statement statementSol = connection.createStatement(); 
            ResultSet resultSetEstrellas = statementSol.executeQuery(sqlEstrellas);
                if (resultSetEstrellas.next()) {
                    // Actualizar los JLabel del sol
                    jLabel_estrella.setText(resultSetEstrellas.getString("nombre"));
                    jLabel_radioEstrella.setText(resultSetEstrellas.getString("radio_km")+" km");
                    jLabel_distanciaEstrella.setText(resultSetEstrellas.getString("distancia_media_tierra_mkm")+" Gm");
                    jLabel_temperaturaEstrella.setText(resultSetEstrellas.getString("temperatura_superficial_c")+" ºC");
                    jLabel_tipoEstrella.setText(resultSetEstrellas.getString("tipo_estrella"));
                    String originalString = resultSetEstrellas.getString("composicion");

                    // Dividir los componentes en tres lineas
                    String[] partes = originalString.split(", ");
                    String resultado = "<html>";
                    for (String parte : partes) {
                        resultado += parte + "<p>";
                    }
                    resultado += "<html>";
                    jLabel_composicionEstrella.setText(resultado);

                }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_estrella = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_tipoEstrella = new javax.swing.JLabel();
        jLabel_radioEstrella = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_temperaturaEstrella = new javax.swing.JLabel();
        jLabel_distanciaEstrella = new javax.swing.JLabel();
        jLabel_composicionEstrella = new javax.swing.JLabel();
        ComboBox_planetas = new javax.swing.JComboBox<>();
        ComboBox_satelites = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel_planeta = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_radioPlaneta = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabeltexto_satelite = new javax.swing.JLabel();
        jLabeltexto_radioSatelite = new javax.swing.JLabel();
        jLabeltexto_distanciaSatelite = new javax.swing.JLabel();
        jLabeltexto_periodoSatelite = new javax.swing.JLabel();
        jLabeltexto_temperaturaSatelite = new javax.swing.JLabel();
        jLabeltexto_tipoSatelite = new javax.swing.JLabel();
        jLabel_distanciaPlaneta = new javax.swing.JLabel();
        jLabel_periodoPlaneta = new javax.swing.JLabel();
        jLabel_temperaturaPlaneta = new javax.swing.JLabel();
        jLabel_TipoPlaneta = new javax.swing.JLabel();
        jLabel_numSatelites = new javax.swing.JLabel();
        jLabel_radioSatelite = new javax.swing.JLabel();
        jLabel_distanciaSatelite = new javax.swing.JLabel();
        jLabel_periodoSatelite = new javax.swing.JLabel();
        jLabel_temperaturaSatelite = new javax.swing.JLabel();
        jLabel_tipoSatelite = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_Satelite = new javax.swing.JLabel();
        jLabel_fotoPlaneta = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_fotoSatelite = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_fechaPlaneta = new javax.swing.JLabel();
        jLabeltexto_fechaSatelite = new javax.swing.JLabel();
        jLabel_fechaSatelite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(4, 4, 6));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Estrella:");

        jLabel_estrella.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel_estrella.setText("Sol");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de estrella:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel4.setText("Radio:");

        jLabel_tipoEstrella.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel_tipoEstrella.setText("asdfa");

        jLabel_radioEstrella.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel_radioEstrella.setText("asdfas");

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel7.setText("Temperatura: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel8.setText("Distacia Media:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel9.setText("Composicion:");

        jLabel_temperaturaEstrella.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel_temperaturaEstrella.setText("asfas");

        jLabel_distanciaEstrella.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel_distanciaEstrella.setText("asdfa");

        jLabel_composicionEstrella.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel_composicionEstrella.setText("asdf");

        ComboBox_planetas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ComboBox_planetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_planetasActionPerformed(evt);
            }
        });

        ComboBox_satelites.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ComboBox_satelites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_satelitesActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sol.jpg"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Planeta:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel16.setText("Planetas:");

        jLabel_planeta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_planeta.setText("jLabel15");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Radio:");

        jLabel_radioPlaneta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_radioPlaneta.setText("jLabel18");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Distancia Media:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Periodo Orbital:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Temperatura Media:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Tipo de Planeta:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Numero de Satelites:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Satelites:");

        jLabeltexto_satelite.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabeltexto_satelite.setText("Satelite:");

        jLabeltexto_radioSatelite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabeltexto_radioSatelite.setText("Radio:");

        jLabeltexto_distanciaSatelite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabeltexto_distanciaSatelite.setText("Distancia Media:");

        jLabeltexto_periodoSatelite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabeltexto_periodoSatelite.setText("Periodo Orbital:");

        jLabeltexto_temperaturaSatelite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabeltexto_temperaturaSatelite.setText("Temperatura Media:");

        jLabeltexto_tipoSatelite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabeltexto_tipoSatelite.setText("Tipo de Cuerpo:");

        jLabel_distanciaPlaneta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_distanciaPlaneta.setText("jLabel31");

        jLabel_periodoPlaneta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_periodoPlaneta.setText("jLabel32");

        jLabel_temperaturaPlaneta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_temperaturaPlaneta.setText("jLabel33");

        jLabel_TipoPlaneta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_TipoPlaneta.setText("jLabel34");

        jLabel_numSatelites.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_numSatelites.setText("jLabel35");

        jLabel_radioSatelite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_radioSatelite.setText("jLabel36");

        jLabel_distanciaSatelite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_distanciaSatelite.setText("jLabel37");

        jLabel_periodoSatelite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_periodoSatelite.setText("jLabel38");

        jLabel_temperaturaSatelite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_temperaturaSatelite.setText("jLabel39");

        jLabel_tipoSatelite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_tipoSatelite.setText("jLabel40");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_Satelite.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Satelite.setText("jLabel41");

        jLabel_fotoPlaneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tierra.jpg"))); // NOI18N

        jLabel_fotoSatelite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Luna.jpg"))); // NOI18N
        jLabel_fotoSatelite.setText("jLabel5");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha creacion:");

        jLabel_fechaPlaneta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_fechaPlaneta.setText("jLabel5");

        jLabeltexto_fechaSatelite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltexto_fechaSatelite.setText("Fecha creación:");

        jLabel_fechaSatelite.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_fechaSatelite.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel_estrella))
                            .addComponent(jLabel13))
                        .addGap(48, 48, 48)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_radioEstrella))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_tipoEstrella))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_temperaturaEstrella))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox_planetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_distanciaEstrella))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel_composicionEstrella)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBox_satelites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_planeta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltexto_radioSatelite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_radioSatelite))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltexto_periodoSatelite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_periodoSatelite))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltexto_satelite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Satelite))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltexto_distanciaSatelite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_distanciaSatelite))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltexto_temperaturaSatelite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_temperaturaSatelite))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_radioPlaneta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_distanciaPlaneta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_periodoPlaneta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_temperaturaPlaneta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltexto_tipoSatelite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_tipoSatelite, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_numSatelites))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_TipoPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltexto_fechaSatelite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_fechaSatelite))
                            .addComponent(jLabel_fotoPlaneta)
                            .addComponent(jLabel_fotoSatelite, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_fechaPlaneta))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel_planeta))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel_radioPlaneta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel_distanciaPlaneta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel_periodoPlaneta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel_temperaturaPlaneta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel_TipoPlaneta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel_numSatelites))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(ComboBox_satelites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel_estrella))
                                .addGap(55, 55, 55)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel_fotoPlaneta)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel_fechaPlaneta))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabeltexto_satelite)
                                            .addComponent(jLabel_Satelite))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabeltexto_radioSatelite)
                                            .addComponent(jLabel_radioSatelite))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabeltexto_distanciaSatelite)
                                            .addComponent(jLabel_distanciaSatelite))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabeltexto_periodoSatelite)
                                            .addComponent(jLabel_periodoSatelite))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabeltexto_temperaturaSatelite)
                                            .addComponent(jLabel_temperaturaSatelite))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabeltexto_tipoSatelite)
                                            .addComponent(jLabel_tipoSatelite)))
                                    .addComponent(jLabel_fotoSatelite, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabeltexto_fechaSatelite)
                                    .addComponent(jLabel_fechaSatelite))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_tipoEstrella)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel_radioEstrella))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_temperaturaEstrella)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel_distanciaEstrella))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel_composicionEstrella))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBox_planetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(62, 62, 62))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_planetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_planetasActionPerformed
        // TODO add your handling code here:
        String selectedPlanet = (String) ComboBox_planetas.getSelectedItem();
        updateSatelitesComboBox(selectedPlanet);
        updatePlanetInfo(selectedPlanet);
        changeVisibilitySatelite(false);
    }//GEN-LAST:event_ComboBox_planetasActionPerformed

    private void ComboBox_satelitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_satelitesActionPerformed
        // TODO add your handling code here:
        String selectedSatelite = (String) ComboBox_satelites.getSelectedItem();
        updateSateliteInfo(selectedSatelite);
        changeVisibilitySatelite(true);
    }//GEN-LAST:event_ComboBox_satelitesActionPerformed
    private void updateSatelitesComboBox(String planeta) {
        ComboBox_satelites.removeAllItems();
        ArrayList<String> satelites = optionsMap.get(planeta);
        if (satelites != null) {
            for (String satelite : satelites) {
                ComboBox_satelites.addItem(satelite);
            }
        }
    }

    private void updatePlanetInfo(String nombrePlaneta) {
        try {
            Connection connection = DatabaseConnection.getConnection();
            // Consulta SQL para obtener la información del planeta seleccionado
            String sql = "SELECT * FROM planetas WHERE nombre = ?";
            PreparedStatement statementPlanetaDetails = connection.prepareStatement(sql);
            statementPlanetaDetails.setString(1, nombrePlaneta);
            ResultSet resultSetPlaneta = statementPlanetaDetails.executeQuery();

            if (resultSetPlaneta.next()) {
                // Actualizar los JLabel con la información del planeta
                jLabel_planeta.setText(resultSetPlaneta.getString("nombre"));
                jLabel_radioPlaneta.setText(resultSetPlaneta.getString("radio_km")+" km");
                jLabel_distanciaPlaneta.setText(resultSetPlaneta.getString("distancia_media_sol_mkm")+" Gm");
                jLabel_periodoPlaneta.setText(resultSetPlaneta.getString("periodo_orbital_dias")+" dias");
                jLabel_temperaturaPlaneta.setText(resultSetPlaneta.getString("temperatura_media_c")+" ºC");
                jLabel_TipoPlaneta.setText(resultSetPlaneta.getString("tipo_planeta"));
                jLabel_numSatelites.setText(resultSetPlaneta.getString("numero_satelites"));
                jLabel_fechaPlaneta.setText(resultSetPlaneta.getString("fecha_creacion"));

                // Nombre del archivo de la imagen
                String imageFileName = resultSetPlaneta.getString("nombre") + ".jpg";

                // Cargar la imagen
                ImageIcon planetImage = new ImageIcon(getClass().getResource("/" + imageFileName));

                // Cambiar el icon del jLabel
                jLabel_fotoPlaneta.setIcon(planetImage);
                
                resultSetPlaneta.close();
                statementPlanetaDetails.close();
                connection.close();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener la información del planeta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateSateliteInfo(String nombreSatelite) {
        try {
            Connection connection = DatabaseConnection.getConnection();
            String sqlSateliteDetails = "SELECT * FROM satelites WHERE nombre = ?";
            PreparedStatement statementSateliteDetails = connection.prepareStatement(sqlSateliteDetails);
            statementSateliteDetails.setString(1, nombreSatelite);
            ResultSet resultSetSatelite = statementSateliteDetails.executeQuery();
            if (resultSetSatelite.next()) {
                jLabel_Satelite.setText(resultSetSatelite.getString("nombre"));
                jLabel_radioSatelite.setText(resultSetSatelite.getString("radio_km")+" km");
                jLabel_distanciaSatelite.setText(resultSetSatelite.getString("distancia_media_planeta_km")+" km");
                jLabel_periodoSatelite.setText(resultSetSatelite.getString("periodo_orbital_dias")+" dias");
                jLabel_temperaturaSatelite.setText(resultSetSatelite.getString("temperatura_media_c")+" ºC");
                jLabel_tipoSatelite.setText(resultSetSatelite.getString("tipo_cuerpo"));
                jLabel_fechaSatelite.setText(resultSetSatelite.getString("fecha_creacion"));

                // Nombre del archivo de la imagen
                String imageFileName = resultSetSatelite.getString("nombre") + ".jpg";

                // Cargar la imagen
                ImageIcon SateliteImage = new ImageIcon(getClass().getResource("/" + imageFileName));

                // Cambiar el icon del jLabel
                jLabel_fotoSatelite.setIcon(SateliteImage);
                
            resultSetSatelite.close();
            statementSateliteDetails.close();
            connection.close();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los detalles del satélite: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void changeVisibilitySatelite(boolean visibilidad){
                jLabel_Satelite.setVisible(visibilidad);
                jLabel_radioSatelite.setVisible(visibilidad);
                jLabel_distanciaSatelite.setVisible(visibilidad);
                jLabel_periodoSatelite.setVisible(visibilidad);
                jLabel_temperaturaSatelite.setVisible(visibilidad);
                jLabel_tipoSatelite.setVisible(visibilidad);
                jLabel_fotoSatelite.setVisible(visibilidad);
                jLabeltexto_satelite.setVisible(visibilidad);
                jLabeltexto_radioSatelite.setVisible(visibilidad);
                jLabeltexto_distanciaSatelite.setVisible(visibilidad);
                jLabeltexto_periodoSatelite.setVisible(visibilidad);
                jLabeltexto_temperaturaSatelite.setVisible(visibilidad);
                jLabeltexto_tipoSatelite.setVisible(visibilidad);
                jLabel_fechaSatelite.setVisible(visibilidad);
                jLabeltexto_fechaSatelite.setVisible(visibilidad);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_planetas;
    private javax.swing.JComboBox<String> ComboBox_satelites;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Satelite;
    private javax.swing.JLabel jLabel_TipoPlaneta;
    private javax.swing.JLabel jLabel_composicionEstrella;
    private javax.swing.JLabel jLabel_distanciaEstrella;
    private javax.swing.JLabel jLabel_distanciaPlaneta;
    private javax.swing.JLabel jLabel_distanciaSatelite;
    private javax.swing.JLabel jLabel_estrella;
    private javax.swing.JLabel jLabel_fechaPlaneta;
    private javax.swing.JLabel jLabel_fechaSatelite;
    private javax.swing.JLabel jLabel_fotoPlaneta;
    private javax.swing.JLabel jLabel_fotoSatelite;
    private javax.swing.JLabel jLabel_numSatelites;
    private javax.swing.JLabel jLabel_periodoPlaneta;
    private javax.swing.JLabel jLabel_periodoSatelite;
    private javax.swing.JLabel jLabel_planeta;
    private javax.swing.JLabel jLabel_radioEstrella;
    private javax.swing.JLabel jLabel_radioPlaneta;
    private javax.swing.JLabel jLabel_radioSatelite;
    private javax.swing.JLabel jLabel_temperaturaEstrella;
    private javax.swing.JLabel jLabel_temperaturaPlaneta;
    private javax.swing.JLabel jLabel_temperaturaSatelite;
    private javax.swing.JLabel jLabel_tipoEstrella;
    private javax.swing.JLabel jLabel_tipoSatelite;
    private javax.swing.JLabel jLabeltexto_distanciaSatelite;
    private javax.swing.JLabel jLabeltexto_fechaSatelite;
    private javax.swing.JLabel jLabeltexto_periodoSatelite;
    private javax.swing.JLabel jLabeltexto_radioSatelite;
    private javax.swing.JLabel jLabeltexto_satelite;
    private javax.swing.JLabel jLabeltexto_temperaturaSatelite;
    private javax.swing.JLabel jLabeltexto_tipoSatelite;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
